# https://wiki.archlinux.org/index.php/Wacom_Tablet

xsetwacom --set "Wacom Bamboo 16FG 4x5 Pen stylus" PressureCurve 0 15 85 100
xsetwacom --set "Wacom Bamboo 16FG 4x5 Finger pad" Button 1 "key 7"
xsetwacom --set "Wacom Bamboo 16FG 4x5 Finger pad" Button 9 "key 6"
xsetwacom --set "Wacom Bamboo 16FG 4x5 Finger pad" Button 8 "key +shift 9"
xsetwacom --set "Wacom Bamboo 16FG 4x5 Finger pad" Button 3 "key +shift 8"

xsetwacom --set "Wacom Bamboo 16FG 4x5 Finger pad" Touch off
 